# Generated by Django 3.2.3 on 2021-05-18 13:14

from django.db import migrations
from django.core.management import call_command
from django.core.serializers import base, python
import pathlib
import logging

logger = logging.getLogger(__name__)


def load_fixture(apps, schema_editor):
    old_get_model = python._get_model

    def _get_model(model_identifier):
        try:
            return apps.get_model(model_identifier)
        except (LookupError, TypeError):
            raise base.DeserializationError(
                "Invalid model identifier: '%s'" % model_identifier)

    python._get_model = _get_model
    try:
        fixture_files = list(pathlib.Path().glob('users/fixtures/0006*.json'))
        logger.info("%s fixture files", fixture_files)
        call_command('loaddata', *fixture_files, app_label='users')
        fixture_files = list(pathlib.Path().glob('users/fixtures/0007*.json'))
        logger.info("%s fixture files", fixture_files)
        call_command('loaddata', *fixture_files, app_label='users')
    finally:
        python._get_model = old_get_model


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210518_1358'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
