# Generated by Django 3.1.7 on 2021-05-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210513_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profile',
            new_name='user',
        ),
    ]
