# Generated by Django 3.2.3 on 2021-06-17 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_last_name_to_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='analytics_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
