# Generated by Django 3.1.7 on 2021-04-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_choice_choice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
    ]
