# Generated by Django 3.1.7 on 2021-05-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_organisation_organisationregion_organisationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('intro_text', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=80, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=80, unique=True)),
                ('intro_text', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('pathway_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.pathwaygroup')),
            ],
        ),
    ]
