# Generated by Django 3.2.3 on 2021-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='controls',
            field=models.ManyToManyField(to='assessment.Control'),
        ),
    ]
