# Generated by Django 3.2.3 on 2021-05-18 15:28

from django.db import migrations, models
import django.db.models.deletion
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_pathway_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.control')),
            ],
            options={
                'order_with_respect_to': 'control',
                'unique_together': {('control', 'sort_order')},
            },
        ),
    ]
