# Generated by Django 3.2.3 on 2021-05-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_auto_20210518_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='control',
        ),
        migrations.AddField(
            model_name='question',
            name='sub_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.subcontrol'),
        ),
    ]
