# Generated by Django 3.2.3 on 2021-05-19 09:33

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20210519_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort'),
        ),
    ]
