# Generated by Django 3.2.3 on 2021-05-19 14:28

from django.core.management import call_command
from django.core.serializers import base, python
from django.db import migrations
import pathlib
import logging

logger = logging.getLogger(__name__)


def remove_answers(apps, schema_editor):
    answer = apps.get_model("assessment", "answer")
    answer.objects.all().delete()

def remove_questions(apps, schema_editor):
    question = apps.get_model("assessment", "question")
    question.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_auto_20210519_1345'),
    ]

    operations = [
        migrations.RunPython(remove_answers),
        migrations.RunPython(remove_questions),
    ]
