# Generated by Django 3.2.3 on 2021-05-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_remove_existing_questions_and_answers'),
        ('assessment', '0019_clear_sample_data'),
    ]

    operations = [
    ]
