# Generated by Django 3.2.3 on 2021-06-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_merge_20210527_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='OrganisationRegion',
        ),
        migrations.DeleteModel(
            name='OrganisationType',
        ),
    ]
