"""
Django settings for CyberHealth project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import environ
import os
from pathlib import Path
import logging
import sys
from django.contrib.staticfiles import finders

logger = logging.getLogger(__name__)
from notifications_python_client.notifications import NotificationsAPIClient


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ABS_ROOT = os.path.abspath(os.path.dirname(__name__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

env = environ.Env(DEBUG=(bool, True))
environ.Env.read_env()

# This application requires a secret key to be set in the environment to be run
SECRET_KEY = env('SECRET_KEY')

# This application requires a debug flag to be set

DEBUG = env('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.london.cloudapps.digital']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'admintheme.apps.AdminthemeConfig',
    'staticpages.apps.StaticpagesConfig',
    'assessment.apps.AssessmentConfig',
    'tinymce',
    'users.apps.UsersConfig',
    'crispy_forms',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sort_order_field',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CyberHealth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'apptemplates.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'CyberHealth.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# https://django-environ.readthedocs.io/en/latest/
# This relies on DATABASE_URL being available in the environment

DATABASES = {
    'default': env.db()
}

# Set the default AutoField type for auto-created model primary keys
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = os.path.join(BASE_DIR, 'static/')
STATIC_ROOT = os.path.join(STATIC_URL, 'assets')
STATICFILES_DIRS = [
    os.path.join(STATIC_URL, 'dist'),
]

# # S3 Asset Storage
DEFAULT_FILE_STORAGE = 'CyberHealth.storage_backends.UploadStorage'
MEDIAFILES_LOCATION = 'uploads'
AWS_ACCESS_KEY_ID = env('S3_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('S3_SECRET')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_DEFAULT_ACL = None
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# in dev + travis:
######## AWS_S3_CUSTOM_DOMAIN = http:localhost:5000/nialls-cool-bucket
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')  # http://localhost:5000
AWS_S3_CUSTOM_DOMAIN = '%s/%s' % (AWS_S3_ENDPOINT_URL, AWS_STORAGE_BUCKET_NAME)
MEDIA_URL = "%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)

# in deployed instance:
### this is the default pattern, so we can disregard this 
###      using a boolean in 'CyberHealth.storage_backends.UploadStorage'
######## AWS_S3_CUSTOM_DOMAIN = nialls-cool-bucket.s3.amazonaws.com
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
### we don't need to specify the endpoint

# AWS_S3_SIGNATURE_VERSION = 's3v4'
# AWS_S3_VERIFY = True


CRISPY_TEMPLATE_PACK = 'bootstrap4'
NOTIFICATIONS_CLIENT = NotificationsAPIClient(env('GOVUK_NOTIFY_KEY'))
LOGIN_REDIRECT_URL = 'assessment-overview'
LOGIN_URL = 'login'
EMAIL_BACKEND = 'django_gov_notify.backends.NotifyEmailBackend'
GOVUK_NOTIFY_API_KEY = env('GOVUK_NOTIFY_KEY')
GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID = 'b5d742c9-39a3-4c9e-82a9-5e79554cbf99'

# Adding in logging
# If you're following the Twelve-Factor App methodology for your application,
# then you'll want to send your logs to Stdout.
# https://odwyer.software/blog/logging-to-standard-output-with-django

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose'
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console'],
            'propagate': False,
            'level': 'WARNING'
        }
    },
}

# Configuration of CORS
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/cyberhealth[^.]*\.london\.cloudapps\.digital$",
    r"^https?://127\.0\.0\.1:\d{4}$",
    r"^https?://localhost:\d{4}$",
    r"^https?:\/\/cyberhealth\.containers\.piwik\.pro$"
]

TINYMCE_JS_URL = os.path.join(STATIC_URL, "tinymce/tinymce.min.js")
TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT, "tinymce/tinymce.min.js")

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "plugins": "code,autolink,lists,link,image,charmap,print,preview,anchor,"
               "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
               "code,help,wordcount",
    "toolbar": "undo redo | styleselect | bold italic"
               " | bullist numlist outdent indent | removeformat | code | help",
    "content_css": "/Users/joelstobart/cyber-health-frontend/CyberHealth/static/css/typography.css",
    "style_formats_merge": False,
    "style_formats":
        [
            {
                "title": "Paragraph",
                "format": "p"
            },
            {
                "title": ".gov.uk Text",
                "items": [
                    {
                        "title": "Lead Paragraph Text",
                        "format": "p-lead",
                        "exact": True
                    },
                    {
                        "title": "Small Paragraph Text",
                        "format": "p-small"
                    },
                    {
                        "title": "Bold Paragraph Text",
                        "format": "p-bold"
                    },
                ]
            },
            {
                "title": ".gov.uk Headings",
                "items": [
                    {
                        "title": "H1", "items": [
                            {
                                "title": "H1 eXtra Large",
                                "format": "govuk-heading1-xl"
                            },
                            {
                                "title": "H1 Large",
                                "format": "h1"
                            },
                            {
                                "title": "H1 Medium",
                                "format": "govuk-heading1-m"
                            },
                            {
                                "title": "H1 Small",
                                "format": "govuk-heading1-s"
                            },
                        ]
                    },
                    {
                        "title": "H2", "items":
                        [
                            {
                                "title": "H2 eXtra Large",
                                "format": "govuk-heading2-xl"
                            },
                            {
                                "title": "H2 Large",
                                "format": "govuk-heading2-l"
                            },
                            {
                                "title": "H2 Medium",
                                "format": "h2"
                            },
                            {
                                "title": "H2 Small",
                                "format": "govuk-heading2-s"
                            },
                        ]
                    },
                    {
                        "title": "H3", "items":
                        [
                            {
                                "title": "H3 eXtra Large",
                                "format": "govuk-heading3-xl"
                            },
                            {
                                "title": "H3 Large",
                                "format": "govuk-heading3-l"
                            },
                            {
                                "title": "H3 Medium",
                                "format": "h3"
                            },
                            {
                                "title": "H3 Small",
                                "format": "govuk-heading3-s"
                            },
                        ]
                    },
                    {
                        "title": "H4", "items":
                        [
                            {
                                "title": "H4 eXtra Large",
                                "format": "govuk-heading4-xl"
                            },
                            {
                                "title": "H4 Large",
                                "format": "govuk-heading4-l"
                            },
                            {
                                "title": "H4 Medium",
                                "format": "govuk-heading4-m"
                            },
                            {
                                "title": "H4 Small",
                                "format": "h4"
                            },
                        ]
                    },
                    {
                        "title": "H5", "items":
                        [
                            {
                                "title": "H5 eXtra Large",
                                "format": "govuk-heading5-xl"
                            },
                            {
                                "title": "H5 Large",
                                "format": "govuk-heading5-l"
                            },
                            {
                                "title": "H5 Medium",
                                "format": "govuk-heading5-m"
                            },
                            {
                                "title": "H5 Small",
                                "format": "h5"
                            },
                        ]
                    },
                    {
                        "title": "Captions", "items":
                        [
                            {
                                "title": "Caption Large",
                                "format": "govuk-caption-l"
                            },
                            {
                                "title": "Caption Medium",
                                "format": "govuk-caption-m"
                            },
                            {
                                "title": "Caption Small",
                                "format": "govuk-caption-s"
                            },
                        ]
                    },
                ]
            },
            {
                "title": ".gov.uk Lists",
                "items": [
                    {
                        "title": "Gov.uk Bullet List",
                        "format": "ul",
                        "exact": True
                    },
                    {
                        "title": "Gov.uk Number List",
                        "format": "ol",
                        "exact": True
                    },
                ]
            }

        ],
    "formats":
        {

            "p": {"block": "p", "classes": "govuk-body"},
            "p-lead": {"block": "p", "classes": "govuk-body-l"},
            "p-small": {"block": "p", "classes": "govuk-body-s"},
            "p-bold": {"block": "p", "classes": "govuk-!-font-weight-bold"},

            "h1": {"block": "h1", "classes": "govuk-heading-l"},
            "h2": {"block": "h2", "classes": "govuk-heading-m"},
            "h3": {"block": "h3", "classes": "govuk-heading-m"},
            "h4": {"block": "h4", "classes": "govuk-heading-s"},
            "h5": {"block": "h5", "classes": "govuk-heading-s"},

            "govuk-heading1-xl": {"block": "h1", "classes": "govuk-heading-xl"},
            "govuk-heading1-m": {"block": "h1", "classes": "govuk-heading-m"},
            "govuk-heading1-s": {"block": "h1", "classes": "govuk-heading-s"},

            "govuk-heading2-xl": {"block": "h2", "classes": "govuk-heading-xl"},
            "govuk-heading2-l": {"block": "h2", "classes": "govuk-heading-l"},
            "govuk-heading2-s": {"block": "h2", "classes": "govuk-heading-s"},

            "govuk-heading3-xl": {"block": "h3", "classes": "govuk-heading-xl"},
            "govuk-heading3-l": {"block": "h3", "classes": "govuk-heading-l"},
            "govuk-heading3-s": {"block": "h3", "classes": "govuk-heading-s"},

            "govuk-heading4-xl": {"block": "h4", "classes": "govuk-heading-xl"},
            "govuk-heading4-l": {"block": "h4", "classes": "govuk-heading-l"},
            "govuk-heading4-m": {"block": "h4", "classes": "govuk-heading-m"},

            "govuk-heading5-xl": {"block": "h5", "classes": "govuk-heading-xl"},
            "govuk-heading5-l": {"block": "h5", "classes": "govuk-heading-l"},
            "govuk-heading5-m": {"block": "h5", "classes": "govuk-heading-m"},

            "heading-caption-l": {"inline": "span", "classes": "govuk-caption-l"},
            "heading-caption-m": {"inline": "span", "classes": "govuk-caption-m"},
            "heading-caption-s": {"inline": "span", "classes": "govuk-caption-s"},


            "bold": {"inline": "strong"},
            "a": {"inline": "a", "classes": "govuk-link"},

            "ul": {"selector": "ul", "classes": "govuk-list  govuk-list--bullet"},

            "ol": {"selector": "ol", "classes": "govuk-list govuk-list--number"},
            "li": {"block": "li"}
        },
}
TINYMCE_SPELLCHECKER = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']

