#!/bin/bash
# Setup default values

DEFAULT_CLOUDFOUNDRY_API = "https://api.london.cloud.service.gov.uk"
DEFAULT_CLOUDFOUNDRY_SPACE = "sandbox"
DEFAULT_CLOUDFOUNDRY_ORG = "mhclg-local-digital"

# Script cloud foundry

$SCRIPT_CLOUDFOUNDRY_API = "${CLOUDFOUNDRY_API:=DEFAULT_CLOUNDFOUNDRY_API}"
$SCRIPT_CLOUDFOUNDRY_SPACE = "${$1:=DEFAULT_SPACE}"
$SCRIPT_CLOUDFOUNDRY_ORG = "${CLOUDFOUNDRY_SPACE:=DEFAULT_CLOUDFOUNDRY_ORG}"

# Structure 
# The index is the name of each folder containing an application

APPLICATIONS = ( frontend)

for application in "${APPLICATIONS[@]}"
do

    cd $application
    pwd
    echo "CLOUDFOUNDRY_USERNAME:$CLOUDFOUNDRY_USERNAME CLOUDFOUNDRY_PASSWORD:$CLOUDFOUNDRY_PASSWORD SCRIPT_CLOUDFOUNDRY_API:$SCRIPT_CLOUDFOUNDRY_API SCRIPT_CLOUDFOUNDRY_SPACE:$SCRIPT_CLOUDFOUNDRY_SPACE SCRIPT_CLOUDFOUNDRY_ORG:$SCRIPT_CLOUDFOUNDRY_ORG"
    source deploy.sh $CLOUDFOUNDRY_USERNAME $CLOUDFOUNDRY_PASSWORD $SCRIPT_CLOUDFOUNDRY_API $SCRIPT_CLOUDFOUNDRY_SPACE $SCRIPT_CLOUDFOUNDRY_ORG
    cd ..
done